$schema: https://coderabbit.ai/integrations/coderabbit-overrides.v2.json
language: "en"
chat:
  auto_reply: true
reviews:
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: true
path_filters:
  - "!build/**"
  - "!node_modules/**"
  - "!assets/css/*.map"
  - "!logs/**"
auto_review:
  enabled: true
  drafts: false
  base_branches:
    - "main"
    - "develop"
    - "feature/*"
    - "fix/*"
    - "update/*"
path_instructions:
  - path: "**/block.json"
    instructions: |
      Review block.json configuration for WordPress block plugins:
        - Ensure JSON syntax is valid and properly formatted
        - Verify block name, title, description, and category are present
        - Check for correct use of supports, attributes, and styles
        - Validate icon and keywords fields for discoverability
        - Confirm textdomain and namespace usage
        - Ensure block is registered for both frontend and editor
        - Check for accessibility compliance and ARIA attributes
        - Validate custom properties don't conflict with core block functionality
  - path: "**/src/**/*.js"
    instructions: |
      Review JavaScript for WordPress block plugin:
        - Check for proper WordPress script enqueueing in block.json
        - Validate accessibility enhancements don't conflict with core features
        - Ensure performance optimization and avoid unnecessary dependencies
        - Check compatibility with WordPress script loading patterns
        - Verify proper event handling and DOM manipulation
        - Ensure scripts work with both frontend and editor interfaces
  - path: "**/src/**/style.scss"
    instructions: |
      Review SCSS for WordPress block plugin:
        - Prefer block.json configuration over custom CSS when possible
        - Ensure SCSS enhances rather than replaces block.json settings
        - Check for proper use of CSS custom properties from block.json
        - Validate responsive design using consistent breakpoints
        - Ensure accessibility compliance in custom styles
        - Check for performance optimization (minimal CSS, efficient selectors)
        - Verify styles don't conflict with core WordPress block styles
        - Ensure proper CSS organization and maintainability
  - path: "**/src/**/render.php"
    instructions: |
      Review render.php for WordPress block plugin:
        - Ensure server-side rendering follows WordPress block standards
        - Validate secure coding practices (sanitization, validation, escaping)
        - Check for proper use of block attributes and context
        - Ensure compatibility with latest WordPress version
        - Check for performance optimization in render functions
        - Ensure functions don't conflict with block editor functionality
  - path: "**/tests/*.{js,php}"
    instructions: |
      Review test files for WordPress block plugin:
        - Ensure valid syntax, logical structure, and clear instructions
        - Check for descriptive test names and clear test structure
        - Include both positive and negative test cases
        - Reference the block or feature under test
        - Be linted and pass all style checks
        - Ensure tests have comprehensive inline documentation
