name: Agent Workflow

on:
    workflow_dispatch:

jobs:
    agent-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
            - name: Run agent script
              run: |
                  node .github/agents/agent-script.js --from-workflow
              env:
                  DRY_RUN: false
                  VERBOSE: true
            - name: Upload agent output
              uses: actions/upload-artifact@v4
              with:
                  name: agent-output
                  path: agent-output.json
