name: WordPress.org SVN Deploy

# Deploy to WordPress.org Plugin Repository
# Requires SVN_USERNAME and SVN_PASSWORD secrets

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy (e.g., 1.2.3)'
        required: true
        type: string
      dry_run:
        description: 'Dry run (do not commit to SVN)'
        required: false
        type: boolean
        default: false

permissions:
  contents: read

env:
  SLUG: '{{slug}}'
  SVN_URL: 'https://plugins.svn.wordpress.org/{{slug}}'

jobs:
  validate:
    name: Validate Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION="${{ inputs.version }}"
          else
            VERSION="${{ github.event.release.tag_name }}"
            VERSION="${VERSION#v}"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "📦 Deploying version: $VERSION"

      - name: Validate version format
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          if ! [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+)?$ ]]; then
            echo "❌ Invalid version format: $VERSION"
            echo "Version must follow semver (e.g., 1.2.3 or 1.2.3-beta1)"
            exit 1
          fi
          echo "✅ Valid version format: $VERSION"

      - name: Check version in plugin file
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          PLUGIN_VERSION=$(grep -oP "Version:\s*\K[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+)?" {{slug}}.php || echo "")
          if [ "$PLUGIN_VERSION" != "$VERSION" ]; then
            echo "❌ Version mismatch!"
            echo "   Tag version: $VERSION"
            echo "   Plugin file version: $PLUGIN_VERSION"
            echo "Run 'npm run update-version -- $VERSION' before releasing."
            exit 1
          fi
          echo "✅ Version matches in plugin file"

  build:
    name: Build Plugin
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - name: Install dependencies
        run: |
          npm ci
          composer install --no-dev --optimize-autoloader

      - name: Build assets
        run: npm run build

      - name: Create distribution
        run: |
          mkdir -p dist/${{ env.SLUG }}

          # Copy plugin files (respecting .distignore)
          rsync -av --exclude-from='.distignore' . dist/${{ env.SLUG }}/

          # Ensure essential files exist
          for file in readme.txt {{slug}}.php; do
            if [ ! -f "dist/${{ env.SLUG }}/$file" ]; then
              echo "❌ Missing required file: $file"
              exit 1
            fi
          done

          echo "✅ Distribution package created"
          ls -la dist/${{ env.SLUG }}/

      - name: Upload distribution artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-dist
          path: dist/${{ env.SLUG }}
          retention-days: 7

  deploy-svn:
    name: Deploy to WordPress.org SVN
    runs-on: ubuntu-latest
    needs: [validate, build]
    environment: wordpress-org

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download distribution
        uses: actions/download-artifact@v4
        with:
          name: plugin-dist
          path: dist/${{ env.SLUG }}

      - name: Install SVN
        run: sudo apt-get update && sudo apt-get install -y subversion

      - name: Checkout SVN repository
        run: |
          echo "📥 Checking out SVN repository..."
          svn checkout --depth=empty ${{ env.SVN_URL }} svn
          cd svn
          svn update --set-depth=infinity trunk
          svn update --set-depth=empty tags
          svn update --set-depth=empty assets

      - name: Copy trunk files
        run: |
          echo "📁 Updating trunk..."
          # Clear trunk (except .svn)
          find svn/trunk -mindepth 1 -maxdepth 1 ! -name '.svn' -exec rm -rf {} \;

          # Copy new files
          cp -r dist/${{ env.SLUG }}/* svn/trunk/

          echo "✅ Trunk updated"

      - name: Copy assets
        run: |
          echo "🖼️ Updating assets..."
          if [ -d ".wordpress-org" ]; then
            # Check out assets folder fully
            cd svn && svn update --set-depth=infinity assets && cd ..

            # Copy assets
            cp -r .wordpress-org/* svn/assets/ 2>/dev/null || true

            echo "✅ Assets updated"
          else
            echo "ℹ️ No .wordpress-org directory found, skipping assets"
          fi

      - name: Create tag
        run: |
          VERSION="${{ needs.validate.outputs.version }}"
          echo "🏷️ Creating tag: $VERSION"

          cd svn
          svn update --set-depth=infinity tags

          # Create tag from trunk
          if [ -d "tags/$VERSION" ]; then
            echo "⚠️ Tag $VERSION already exists, removing..."
            svn delete "tags/$VERSION"
          fi

          svn copy trunk "tags/$VERSION"
          echo "✅ Tag created"

      - name: Prepare SVN changes
        run: |
          cd svn

          # Add new files
          svn add --force . --auto-props --parents --depth infinity -q 2>/dev/null || true

          # Remove deleted files
          svn status | grep "^\!" | awk '{print $2}' | xargs -r svn delete 2>/dev/null || true

          echo "📋 SVN Status:"
          svn status

      - name: Commit to SVN
        if: ${{ !inputs.dry_run }}
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        run: |
          VERSION="${{ needs.validate.outputs.version }}"
          echo "🚀 Committing version $VERSION to WordPress.org..."

          cd svn
          svn commit \
            --username "$SVN_USERNAME" \
            --password "$SVN_PASSWORD" \
            --no-auth-cache \
            --non-interactive \
            -m "Release version $VERSION"

          echo "✅ Successfully deployed to WordPress.org!"
          echo "🔗 https://wordpress.org/plugins/${{ env.SLUG }}/"

      - name: Dry run summary
        if: ${{ inputs.dry_run }}
        run: |
          echo "🔍 DRY RUN - No changes committed to SVN"
          echo ""
          echo "Would have committed:"
          cd svn && svn status
          echo ""
          echo "To deploy for real, run the workflow again with dry_run unchecked."

  notify:
    name: Notify Deployment
    runs-on: ubuntu-latest
    needs: [validate, deploy-svn]
    if: ${{ !inputs.dry_run && always() }}

    steps:
      - name: Deployment success notification
        if: ${{ needs.deploy-svn.result == 'success' }}
        run: |
          VERSION="${{ needs.validate.outputs.version }}"
          echo "✅ Plugin ${{ env.SLUG }} v$VERSION deployed to WordPress.org!"
          echo ""
          echo "📦 Plugin page: https://wordpress.org/plugins/${{ env.SLUG }}/"
          echo "📥 Download: https://downloads.wordpress.org/plugin/${{ env.SLUG }}.$VERSION.zip"

      - name: Deployment failure notification
        if: ${{ needs.deploy-svn.result == 'failure' }}
        run: |
          echo "❌ Deployment failed!"
          echo "Please check the workflow logs for details."
          exit 1
